use_frameworks!

platform :ios, '13.0'

target 'AsposeCellsSwift_Example' do
  pod 'AsposeCellsSwift', :path => '../'
  pod 'AsposeCellsCloud', '~> 21.7'

  target 'AsposeCellsSwift_Tests' do
    inherit! :search_paths
  end
end
